#!/usr/bin/env bash
set -euo pipefail

spec_glob="*v1_0_4*"
spec_dir="spec"
output_path="paper/spec_hash.tex"
spec_version="1.0.4"

if [[ ! -d "$spec_dir" ]]; then
  echo "Spec directory not found: $spec_dir" >&2
  exit 1
fi

if ! command -v sha256sum >/dev/null 2>&1; then
  echo "sha256sum is required to compute spec hash." >&2
  exit 1
fi

mapfile -d '' spec_files < <(find "$spec_dir" -maxdepth 1 -type f -name "$spec_glob" -print0 | LC_ALL=C sort -z)

if [[ ${#spec_files[@]} -eq 0 ]]; then
  echo "No spec files found matching ${spec_glob} in ${spec_dir}" >&2
  exit 1
fi

spec_hash="$(
  printf '%s\0' "${spec_files[@]}" \
    | xargs -0 sha256sum \
    | LC_ALL=C sort \
    | sha256sum \
    | awk '{print $1}'
)"

spec_files_list="$(printf '%s,' "${spec_files[@]}" | sed 's/,$//')"

cat > "$output_path" <<EOF
% Auto-generated by scripts/write_spec_hash.sh
\\newcommand{\\ARFSpecVersion}{$spec_version}
\\newcommand{\\ARFSpecHash}{sha256:$spec_hash}
\\newcommand{\\ARFSpecFiles}{\\detokenize{$spec_files_list}}
EOF

echo "Wrote spec hash to $output_path"
