#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# shellcheck disable=SC1091
source "$repo_root/SPEC_VERSION"

version_slug="${AARC_VERSION//./_}"
spec_glob="*v${version_slug}*"
spec_dir="spec"
output_path="paper/spec_hash.tex"

if ! command -v sha256sum >/dev/null 2>&1; then
  echo "sha256sum is required to compute spec hash." >&2
  exit 1
fi

mapfile -d '' spec_files < <(
  find "$spec_dir" -maxdepth 1 -type f -name "$spec_glob" -print0 | sort -z
)

if [[ ${#spec_files[@]} -eq 0 ]]; then
  echo "No spec files found matching $spec_glob in $spec_dir" >&2
  exit 1
fi

spec_hash="$(
  printf '%s\0' "${spec_files[@]}" \
    | xargs -0 sha256sum \
    | sha256sum \
    | awk '{print $1}'
)"

cat > "$output_path" <<EOF
% Auto-generated by scripts/write_spec_hash.sh
\\newcommand{\\specHash}{$spec_hash}
\\newcommand{\\specVersion}{$AARC_VERSION}
EOF

echo "Wrote AARC v$AARC_VERSION spec hash to $output_path"
